services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask_app:latest
    container_name: flask_app_container
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - app-network

  web:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/server.crt:/etc/nginx/certs/server.crt
      - ./ssl/server.key:/etc/nginx/certs/server.key
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge