version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask_app:latest
    container_name: flask_app_container
    volumes:
      - .:/app
    env_file:
      - .env
    command: flask run --host=0.0.0.0 --port=5000
    networks:
      - app-network

  web:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "5000:5000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
